pipelion/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('runner.urls')),
    url(r'^admin/', admin.site.urls),
]

runner/urls.py
from django.conf.urls import url, url, include
from django.contrib.auth.decorators import login_required, permission_required
from runner.views import CommandCreate, CommandList, CommandDelete, JobCreate, \
    JobList, JobDelete, LoginOrHome, miso, PipelineCreate, PipelineList, \
    PipelineDelete, run_job


urlpatterns = [
    url('^', include('django.contrib.auth.urls')),
    url(r'^$', LoginOrHome, name='login_or_home'),

    url(r'^miso/$', miso, name='miso'),
    url(r'^new/command/$', login_required(CommandCreate.as_view()), name='command_create'),
    url(r'^new/pipeline/$', login_required(PipelineCreate.as_view()), name='pipeline_create'),
    url(r'^new/job/$', login_required(JobCreate.as_view()), name='job_create'),

    url(r'^list/command/$', login_required(CommandList.as_view()), name='command_list'),
    url(r'^list/pipeline/$', login_required(PipelineList.as_view()), name='pipeline_list'),
    url(r'^list/job/$', login_required(JobList.as_view()), name='job_list'),
    
    url(r'^delete/command/(?P<pk>\d+)/$', login_required(CommandDelete.as_view()), name="command_delete"),
    url(r'^delete/pipeline/(?P<pk>\d+)/$', login_required(PipelineDelete.as_view()), name="pipeline_delete"),
    url(r'^delete/job/(?P<pk>\d+)/$', login_required(JobDelete.as_view()), name="job_delete"),

    url(r'^run/job/(?P<pk>\d+)/$', run_job, name="run_job"),
]

runner/models.py
from __future__ import unicode_literals

from django.db import models

MONITOR_TYPES = ((0, 'No Monitor'), (1, 'Slurm Monitor')) # these need to match up with the list declared in monitors.py
JOB_STATES = ((0, 'not started'), (1, 'running'), (2, 'finished'), (3, 'error'))

class InputKey(models.Model):
    name = models.CharField(max_length=50, unique=True)
    def __str__(self):
        return self.name

class Command(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    command_text = models.CharField(max_length=5000)
    monitor = models.PositiveSmallIntegerField(choices=MONITOR_TYPES, default=0)
    input_keys = models.ManyToManyField(InputKey)
    def __str__(self):
        return self.name
    
class Pipeline(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    commands = models.ManyToManyField(Command)

    def __str__(self):
        return self.name

class Job(models.Model):
    """
    A run of a pipeline
    """
    
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    pipeline = models.ForeignKey(Pipeline)
    input = models.CharField(max_length=10000, default='[]')
    output = models.CharField(max_length=10000, null=True, blank=True)
    error = models.CharField(max_length=10000, null=True, blank=True)
    exit_code = models.CharField(max_length=5, null=True, blank=True)
    state = models.PositiveSmallIntegerField(choices=JOB_STATES, default=0, null=True, blank=True)
    scheduler_state = models.CharField(max_length=500, null=True, blank=True)
    current_command = models.ForeignKey(Command, null=True, blank=True)
    last_run = models.DateTimeField(blank=True, null=True, )
    can_submit = models.BooleanField(blank=False, null=False, default=True)
    def __str__(self):
        return self.name
    

runner/forms.py
from django import forms
from django.forms import ModelForm
from runner.models import Command, Pipeline

runner/views.py
import StringIO
from datetime import datetime
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.core import exceptions
import json
from runner.models import Command, Pipeline, Job, JOB_STATES
from subprocess import CalledProcessError
import subprocess
import thread
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from runner.monitors import monitors, decodestatus
import drmaa
from django.http import JsonResponse
# Non-restful API for integration

def _get_data_for_state(clazz, drmaa_state, serialize=True):
    jobs = clazz.objects.filter(scheduler_state=decodestatus[drmaa_state])
    rtn = []
    for job in jobs:
        jobject = {'id': job.pk, 
            'name': job.name,
            'statusMessage': job.scheduler_state,
            'startDate': job.last_run,
            'pipeline': {'name': job.pipeline.name,
                'processes': []
            }
        }
        for command in job.pipeline.commands.all():
            jobject['pipeline']['processes'].append(command.name)
        rtn.append(jobject)
    if serialize:
        return JsonResponse(rtn, safe=False)
    else:
        return rtn

def get_completed_jobs(request):
    """
    Returns all jobs that have been marked by the scheduler as completed.
    """

    return _get_data_for_state(Job, drmaa.JobState.DONE)

def get_failed_jobs(request):
    """
    Returns all jobs that have been marked by the scheduler as failed.
    """
    
    return _get_data_for_state(Job, drmaa.JobState.FAILED)

def get_running_jobs(request):
    """
    Returns all jobs that have been marked by the scheduler as running.
    """

    return _get_data_for_state(Job, drmaa.JobState.RUNNING)


def get_pending_jobs(request):
    """
    Returns all jobs that have been marked by the scheduler as pending.
    """
    
    rtn = []
    rtn.extend(_get_data_for_state(Job, drmaa.JobState.QUEUED_ACTIVE, False))
    rtn.extend(_get_data_for_state(Job, drmaa.JobState.SYSTEM_ON_HOLD, False))
    rtn.extend(_get_data_for_state(Job, drmaa.JobState.USER_ON_HOLD, False))
    rtn.extend(_get_data_for_state(Job, drmaa.JobState.USER_SYSTEM_ON_HOLD, False))
    rtn.extend(_get_data_for_state(Job, drmaa.JobState.UNDETERMINED, False))
    return JsonResponse(rtn, safe=False)

def get_jobs(request):
    """
    Return all the jobs!
    """
    raise NotImplementedError()
    #return _serialize_objs(Job.objects.all())

def get_job(request):
    """
    Get a job by id.
    POST should look like:
    `{
        'query': 'getPipeline',
        'params': {
           'name': 'taskid'
       }
    }`
    """
    raise NotImplementedError()
#     params = json.loads(request.POST.get('params'))
#     name = params.get("name")
#     return _serialize_objs([Job.objects.get(pk=name)])

def get_pipeline(request):
    """
    Get a pipeline by name.
    POST should look like:
    `{
        'query': 'getPipeline',
        'params': {
           'name': 'pipeline name'
       }
    }`
    """
    rtn = {}
    params = request.POST.get('params')
    name = params.get("name")

    pipeline = Pipeline.objects.get(name=name)
    rtn['name'] = pipeline.name
    processes = []
    all_required_parameters = []
    for command in pipeline.commands.all():
        input_keys = []
        for input_key in command.input_keys.all():
            input_keys.append(input_key.name)
            all_required_parameters.append({'name': input_key.name})
        
        processes.append({'name': command.name, 'parameters': input_keys})
    rtn['processes'] = processes
    rtn['allRequiredParameters'] = all_required_parameters
    return JsonResponse(rtn, safe=False) 

def get_pipelines(request):
    """
    Return all pipeline objects.
    """
    rtn = []
    for pipeline in Pipeline.objects.all():
        obj = {}
        obj['name'] = pipeline.name
        obj['processes'] = []
        for command in pipeline.commands.all():
            obj['processes'].append(command.name)
        rtn.append(obj)
        
    return JsonResponse(rtn, safe=False) 
        
    #return _serialize_objs(Pipeline.objects.all())

def submit_job(request):
    """
    Creates a job from a request object and submits it.
    The request should contain everything needed to start a job:
    """

    name = "pipelion submitted job"
    description = "pipelion submitted job"

    request.POST = request.POST.get('submitTask')

    pipeline = request.POST.get("pipeline")
    params = request.POST.get("params")
    run = True

    if "name" in params:
        name = params.get("name")
    if "description" in params:
        description = params.get("description")
    if "run" in params:
        run = params.get("run")
    job = Job(name=name, description=description, pipeline=Pipeline.objects.get(name=pipeline))
    job.save()
    if run:
        run_job(None, job.pk)
    rtn = {'success': True, 'id': job.pk}
    return JsonResponse(rtn, safe=False) 


@csrf_exempt
def miso(request):
    """
    Marshalls between miso specific API methods based on query.
    """

    # determine if post data is in body or POST :s
    # This seems to be a quirk when calling the API from Java
    post_data = ""
    if not request.POST:
        try:
            request.POST = json.loads(request.body)
        except ValueError:
            error = "No query in POST request"
            return JsonResponse([{ 'success' : False, 'error' : error }], safe=False)

    if request.POST.get('submitTask'):
        query = 'submitTask'
    else:
        query = request.POST.get('query')
    views = {
        "getCompletedTasks": get_completed_jobs,
        "getFailedTasks": get_failed_jobs,
        "getPendingTasks": get_pending_jobs,
        "getPipeline": get_pipeline,
        "getPipelines": get_pipelines,
        "getRunningTasks": get_running_jobs,
        "getTask": get_job,
        "getTasks": get_jobs,
        "submitTask": submit_job,
    }

    result = views[query](request)
    print  'getting {} returning {}'.format( query, result )
    return result
# end of miso specific code.

def run_job(request, pk):
    success_url = '/runner/list_job'
    def run_commands(job):
        # run each command in the pipeline
        job.last_run = datetime.now()
        job.state = 1
        if job.exit_code:
            job.output = None
            job.error = None
            job.exit_code = None
            job.current_command = None
        job.save()
        for command in job.pipeline.commands.all():
            print 'running:'
            print command
            job.current_command = command
            job.save()
            raw_command = command.command_text
            try:
                print 'setting input'
                print job.input
                input = json.loads("[" + job.input + "]")
                for item in input:
                    for placeholder, value in item.iteritems():
                        raw_command = raw_command.replace(placeholder, value)
            except Exception as ex:
                job.error = ex
                job.state = 3
                job.exit_code = -1
                job.save()
                return

            print "executing " + command.command_text
            try:
                p = subprocess.Popen(raw_command, stdin=None, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
                output, output_err = p.communicate()
                job.output = output
                job.error = output_err
                job.exit_code = p.returncode
                job.save()
                # at this point the command has been executed.
                # since this is designed for schedulers this may not be the end of the story!
                # we need a way of monitoring the progress of the job and then reporting back
                # when things have changed.
                if command.monitor != 0:
                    monitor_instance = monitors.get(command.monitor)()
                    monitor_instance.monitor(job)
            except CalledProcessError as cpe:
                job.state = 3
                job.exit_code = cpe.returncode
                job.save()
                raise cpe
            except OSError as ose:
                job.state = 3
                job.exit_code = ose.errno
                job.save()
                raise ose
            except Exception as ex:
                job.state = 3
                job.exit_code = -1
                job.save()
                raise ex
        job.state = 2
        job.save()


    job = Job.objects.get(id=pk)
    thread.start_new_thread (run_commands, (job,))

    return redirect('job_list')

# Views for pipelion ui

class CommandList(ListView):
    queryset = Command.objects.order_by('-id')
    model = Command
    def get_context_data(self, **kwargs):
        context = super(CommandList, self).get_context_data(**kwargs)
        return context

class CommandCreate(CreateView):
    model = Command
    success_url = '/'
    fields = ['name', "description", "command_text"]

class CommandDelete(DeleteView):
    model = Command
    success_url = '/list/command'

class JobCreate(CreateView):
    success_url = '/list/job'
    model = Job
    fields = ['name', "description", "pipeline"]
    def post(self, request):
        new_model = Job()
        new_model.name = request.POST.get('name')
        new_model.description = request.POST.get('description')
        new_model.input = request.POST.get('input_json')
        new_model.pipeline = Pipeline.objects.get(pk=request.POST.get('pipeline'))
        new_model.save()
        return HttpResponseRedirect(self.success_url)

class JobList(ListView):
    queryset = Job.objects.order_by('-id')
    model = Job

runner/templates/runner/base.html
{% load staticfiles %}
<html>
    <head>
        <title>pipelion</title>
        <script
        src="https://code.jquery.com/jquery-2.2.3.min.js"
        integrity="sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo="
        crossorigin="anonymous"></script>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    </head>
    <body>
        <style>
            .fixed-nav-bar {
                position: fixed;
                top: 0;
                left: 0;
                z-index: 9999;
                width: 100%;
                height: 40px;
                background-color: #428bca;
                color: #ffffff;
                display: table;
                font-weight: bold;
            }

        </style>
        <nav class="fixed-nav-bar">
            <span class="glyphicon glyphicon-grain"></span>
            <div style="display: table-cell; vertical-align: middle; padding-left: 10px;">
                <span class="glyphicon glyphicon-send" aria-hidden="true"></span>
                <div id="message-panel" style="display: inline-block;"></div>
                <div style="float: right;">
                    {{ user }} |
                    <a href="/admin/"><span class="label label-danger">Admin Area</span></a>
                    <a href="/logout/?next=/"><span class="label label-default">Logout</span></a>
                </div>
            </div>
        </nav>

        <div class="container" style="margin-top: 10px;">
            <div class="page-header">
                <h1><a href="/">pipelion</a></h1>
            </div>

            {% block nav %}
            {% include "runner/navbar.html" %}
            {% endblock %}

            <div class="container">
                        {% block content %}
                        {% endblock %}
            </div>
        </div>
    </body>
</html>

runner/templates/runner/command_form.html
{% extends 'runner/base.html' %}
{% block content %}

<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock %}

runner/templates/runner/command_list.html
{% extends 'runner/base.html' %}

{% block content %}

<h2>Commands</h2>
<table class="table table-hover">
    <thead>
        <tr>
            <th>Name</th><th>Description</th><th>Command</th><th>Actions</th>
        </tr>
    </thead>
    {% for command in object_list %}
    <tr>
        <td> {{ command.name }} </td>
        <td> {{ command.description }} </td>
        <td> {{ command.command_text }} </td>

        <td>
        <form action="/admin/runner/command/{{ command.id }}/change/">{% csrf_token %}
            <input type="submit" value="Edit" />
        </form></td>
        <td>
        <form action="/delete/command/{{ command.id }}/" method="post">{% csrf_token %}
            <input type="submit" value="Delete" />
        </form></td>
    </tr>
    {% empty %}
    <tr>
        <td> No commands yet. </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

runner/templates/runner/command_update_form.html
{% extends 'runner/base.html' %}
{% block content %}
<h2>Edit Command</h2>
<form>{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
{% endblock %}

runner/templates/runner/job_form.html
{% extends 'runner/base.html' %}
{% block content %}
<h2>Create Job</h2>
<form action="" method="post" id="create_form">
    {% csrf_token %}
    {{ form.as_p }}
    <div id="input_container"></div>
    <input type="button" value="+" id="add_input_btn"/>
    <input type="submit" value="Save" id="save_btn"/>
</form>

<script>
    num_rows = 0;

    function addRow() {
        num_rows++;
        $('#input_container').append("<br />").append("<div style='display:inline-block; margin-top: 10px; margin-right: 10px;'>").append("<b>Placeholder:</b>").append("<input type='text' id='placeholder_" + num_rows + "'" + "/>").append("</div>").append("<div style='display:inline-block; margin:10px;'>").append("<b>Value:</b>").append("<input type='text' id='value_" + num_rows + "'" + "/>").append("</div>");
        return false;
    }


    $(document).ready(function() {
        addRow();
        jQuery("#add_input_btn").click(addRow);
        jQuery("#save_btn").click(function() {
            // create input json
            json = {};
            placeholder = '';
            $("#input_container input[type=text]").each(function() {
                if (this.id.indexOf('placeholder') >= 0) {
                    placeholder = this.value;
                } else {
                    json[placeholder] = this.value;
                    placeholder = '';
                }
            });
            console.log(json);
            var input = $("<input>")
           .attr("type", "hidden")
           .attr("name", "input_json").val(JSON.stringify(json));
            $('#create_form').append($(input));
            $('#create_form').submit();

            return false;
        });
    }); 
</script>

{% endblock %}

runner/templates/runner/job_list.html
{% extends 'runner/base.html' %}
{% block content %}
<style>
    .action-button {
        display: inline-block;
        padding-right: 5px;
    }

</style>
<h2>Jobs</h2>
<div>
    <div class="panel-group" id="accordion">
        {% for job in object_list %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title" id="tr_{{ job.id }}">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{ job.id }}"><span class="glyphicon glyphicon-collapse-down"></span></a>
                    <table class='table table-striped'>
                        <thead>
                            <tr>
                                <th>Last Run</th>
                                <th>Name</th>
                                <th>Pipeline</th>
                                <th>Current Command</th>
                                <th>Console State</th>
                                <th>Exit Code</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{{ job.last_run }}</td>
                                <td>{{job.name }}</td>
                                <td>{{ job.pipeline }}</td>
                                <td>{{ job.current_command }}</td>
                                <td>{{ job.get_state_display }}</td>
                                <td>{{ job.exit_code }} </td>
                                <td><span class="glyphicon glyphicon-play" onclick="return click_run({{ job.id }});"> </span><span class="glyphicon glyphicon-trash" onclick="return click_delete({{ job.id }});"> </span></td>
                                <input type="hidden" value="{{ job.id }}" name="id">
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div id="collapse{{ job.id }}" class="panel-collapse collapse">
                    <div class="panel-body">
                        <div class="panel panel-primary">
                            <div class = "panel-heading">
                                <h3 class = "panel-title">Output</h3>
                            </div>
                            <div id="output_panel{{ job.id }}" class = "panel-body" style="overflow-y: scroll;">
                                {{ job.output|linebreaksbr }}
                            </div>
                        </div>
                        <div class="panel panel-danger">
                            <div class = "panel-heading">
                                <h3 class = "panel-title">Error</h3>
                            </div>
                            <div id="error_panel{{ job.id }}" class = "panel-body" style="overflow-y: scroll;">
                                {{ job.error|linebreaksbr }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <script>
        function click_run(id) {
            jQuery.post("/run/job/" + id + "/", {
                'csrfmiddlewaretoken' : '{{ csrf_token }}'
            }, function(data) {
                $(function() {
                    $('#message-panel').html("Job id " + id + " submitted.  Refresh page.").show().delay(3000).fadeOut(function() {
                        $(this).hide();
                    });
                });
            });
        }

        function click_delete(id) {
            jQuery.post("/delete/job/" + id + "/", {
                'csrfmiddlewaretoken' : '{{ csrf_token }}'
            }, function(data) {
                jQuery("#tr_" + id).remove();
                $(function() {
                    $('#message-panel').html("Job id " + id + " deleted.").show().delay(3000).fadeOut(function() {
                        $(this).hide();
                    });
                });
            });
        }
    </script>
    {% endblock %}

runner/templates/runner/job_update_form.html
{% extends 'runner/base.html' %}
{% block content %}
<h2>Edit Job</h2>
<form>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
{% endblock %}

runner/templates/runner/navbar.html
<nav>
    <ul class="nav nav-pills">
        <li role="presentation">
            <a href="{% url 'job_create' %}">Create Job</a>
        </li>
        <li role="presentation">
            <a href="{% url 'pipeline_create' %}">Create Pipeline</a>
        </li>
        <li role="presentation">
            <a href="{% url 'command_create' %}">Create Command</a>
        </li>
        <li role="presentation">
            <a href="{% url 'job_list' %}">List Jobs</a>
        </li>
        <li role="presentation">
            <a href="{% url 'pipeline_list' %}">List Pipelines</a>
        </li>
        <li role="presentation">
            <a href="{% url 'command_list' %}">List Commands</a>
        </li>
    </ul>
</nav>

runner/templates/runner/pipeline_form.html
{% extends 'runner/base.html' %}
{% block content %}
<h2>Create Pipeline</h2>
<form action="" method="post" id="create_form">
    {% csrf_token %}
    {{ form.as_p }}
    <div style="display: inline-block; margin: 10px;">
        <h3>Available Commands:</h3>

        <select multiple id="available" style="width: 100%;">
            {% for command in commands %}
            <option value="{{ command.id }}">{{ command.name }}</option>

            {% empty %}
            No commands.
            {% endfor %}
        </select>
    </div>
    <div id='move_all_left' style="display: inline-block;">
        <input type="button" value="<<" />
    </div>
    <div id='move_left' style="display: inline-block;">
        <input type="button" value="<" />
    </div>
    <div id='move_right' style="display: inline-block;">
        <input type="button" value=">" />
    </div>
    <div id='move_all_right' style="display: inline-block;">
        <input type="button" value=">>" />
    </div>

    <div style="display: inline-block; margin: 10px;">
        <h3>Selected Commands:</h3>
        <select multiple name="commands[]" id="selected" form="create_form" style="width: 100%;"></select>
    </div>

</form>
<input type="button" value="Save" id="save_btn"/>
<script>
    $(document).ready(function() {
        jQuery("#save_btn").click(function() {
            $('#selected option').prop('selected', true);
            $('#create_form').submit();

            return false;
        });
        $("#move_all_right").click(function() {
            var items = $("#available option").clone();
            var selected = $("#selected");
            items.each(function(index, value) {
                selected.append(value);
            });
            return false;
        });
        $("#move_all_left").click(function() {
            var selected = $("#selected").find('option').remove();
        });
        $("#move_right").click(function() {
            var items = $('#available').find(":selected").clone();
            var selected = $("#selected");
            items.each(function(index, value) {
                selected.append(value);
            });
            return false;
        });
        $("#move_left").click(function() {
            var items = $('#selected').find(":selected").remove();

            return false;
        });
    });

</script>
{% endblock %}

runner/templates/runner/pipeline_list.html
{% extends 'runner/base.html' %}

{% block content %}

<h2>Pipelines</h2>
<table class="table table-hover">
    <thead>
        <tr>
            <th>Name</th><th>Description</th><th>Commands</th><th>Actions</th>
        </tr>
    </thead>
    {% for pipeline in object_list %}
    <tr>
        <td> {{ pipeline.name }} </td>
        <td> {{ pipeline.description }} </td>
        <td> {{ pipeline.commands.count }} </td>

        <td>
        <form action="/admin/runner/pipeline/{{ pipeline.id }}/change/">{% csrf_token %}
            <input type="submit" value="Edit" />
        </form>
        <form action="/delete/pipeline/{{ pipeline.id }}/" method="post">{% csrf_token %}
            <input type="submit" value="Delete" />
        </form></td>
    </tr>
    {% empty %}
    <tr>
        <td> No pipelines yet. </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

runner/templates/runner/pipeline_update_form.html
{% extends 'runner/base.html' %}
{% block content %}
<h2>Edit Pipeline</h2>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
{% endblock %}